version: "3.8"

services:
  gifu-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_CACHE_SIZE=3g
    container_name: gifu-core-service
    ports:
      - "8443:8443"
    expose:
      - 8443
    volumes:
      - /var/opt/app_data/files/picture:/var/data/files/picture
      - /var/opt/certs:/certs