version: "3.8"

services:
  gifu-api:
    build: .
    container_name: gifu-core-service
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - /var/opt/app_data/files/picture:/var/data/files/picture
      - /var/opt/certs:/certs