INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.historical_order_table','historical_order_table','Historical order table',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.confirm_order','confirm_order','Confirm order',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.bill_order','bill_order','Bill order',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.staff_assignment','staff_assignment','Staff assignment',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.product_search','product_search','Search product',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.product_add','product_add','Add product',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.product_edit','product_edit','Edit product',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.catalog_search','catalog_search','Search catalog',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.catalog_add','catalog_add','Add catalog',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.catalog_edit','catalog_edit','Edit catalog',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.catalog_delete','catalog_delete','Delete catalog',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.workflow_search','workflow_search','Search workflow',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.workflow_add','workflow_add','Add workflow',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.workflow_edit','workflow_edit','Edit workflow',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.workflow_delete','workflow_delete','Delete workflow',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.user_search','user_search','Search user',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.user_add','user_add','Add user',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.user_edit','user_edit','Edit user',current_timestamp,current_timestamp);
INSERT INTO public."permission" ("name", code, remarks, created_date, updated_date) VALUES('permisisons.approve_step_status','approve_step_status','Approval step status',current_timestamp,current_timestamp);

